### ISSUE TITLE
csv artifact is always empty

### ISSUE THREAD

**Issue by annescharf** [CodenameGreyFox/DetectionOfStationarity#3] opened 2023-06-22 10:56 UTC
Hi @CodenameGreyFox, I'm going through the apps together with Andrea before sending them out for review. I'm not sure if it is the input data that I am using, or the settings. I've tested several things, but the csv artifact is always empty. Could you maybe check again the app on moveapps and see if its working fine for you? I used the movebank study "LifeTrack White Stork SW Germany" with the individuals, Angela, Betty and Cocco. Thank you.

**Comment by CodenameGreyFox** [comment] 2023-06-22 11:51
Hi. It does give results to me. ~~But while I was testing this, something did seem to be strange.~~

~~In my machine, when I put an allowable error of 0.001 I get only Betty selected. But when I put it in MoveApps it is selecting them all (the reverse problem of what you are having), exactly like if I had given an allowable error of 1.~~

~~As such, I am not sure it is taking the "Allowable GPS Error" correctly.~~ In fact, I can not write "0." as it immediately deletes it. I have to start with the "." for it to work. Is this expected behaviour? Could it be the fault of my appspec.json? I listed the parameter as a DOUBLE as it should take values like 0.001. But is that not correct terminology? Should it be FLOAT or something?

With that said, if you put the allowable error at 1 and the hours at 24, does it give you an empty csv? It doesn't to me.

**Comment by CodenameGreyFox** [comment] 2023-06-22 14:57
Scratch what I said previously. It seems like it was either some bug that went away when I refreshed or I did something wrong. Now it still doesn't allow me to write "0." normally, but it does work as intended when I paste the "0.001" there directly.

What settings were you using to not get any output? For me, with "0.001" as allowable error and 24h as the limit, it gives me Betty as the output.

**Comment by annescharf** [comment] 2023-06-22 19:41
I now ran it again with error=1,  and 24h, and it gave me results. Your appspecs seem to be fine. It seems that there is some kind of bug in the system, because one cannot enter the value e.g. "1.3", only ".01". I'll let you know as soon as I find out what is going on. 

Looking at you appspec, I have a small suggestion. As in "Filter Results?" the user can only choose between 3 values, you could also use "[radiobutton](https://docs.moveapps.org/#/radiobuttons)", the user than just has to click on the wanted option.

**Comment by CodenameGreyFox** [comment] 2023-06-22 20:40
Oh, I did not notice that was an option. I just changed it and updated the app. Thanks for the heads-up.

**Comment by andreakoelzsch** [comment] 2023-06-23 06:40
the new app version is built.
Indeed, tehre is a bug in the system with the double setting not allowing "." to be entered, this is on the list to be fixed next week. thanks for bearing with us!

**Comment by CodenameGreyFox** [comment] 2023-06-23 10:18
Good to know the problem isn't on my side then! Thanks.

**Comment by andreakoelzsch** [comment] 2023-07-04 11:17
Hi @CodenameGreyFox, the issue with the DOUBLE and "." should be fixed now on Moveapps. Please let me know if there are other issues like that or this one does not work yet as you expect it. Thanks!

**Comment by CodenameGreyFox** [comment] 2023-07-04 12:29
Great! Thanks to you too.

**Closed as completed by CodenameGreyFox** 2023-07-04 12:29 UTC
